### ISSUE TITLE
Callback function to handle Select category dropdown interaction not functional

### ISSUE THREAD

**Issue by tpanati** [vyshnavi-adusumelli/FinBot#28]
Testing phase:

![image](https://github.com/vyshnavi-adusumelli/FinBot/assets/144171816/b4756d86-1501-45ba-93fc-ab66910e074f)

![image](https://github.com/vyshnavi-adusumelli/FinBot/assets/144171816/f8888a93-813d-4b6e-9a63-22d26e9ea529)

![image](https://github.com/vyshnavi-adusumelli/FinBot/assets/144171816/da5d4258-a2f5-4911-a36f-0ee97c020fa5)

Everything is working fine except for the callback on selection. The interaction response is not recognized and the following error is encountered:

![image](https://github.com/vyshnavi-adusumelli/FinBot/assets/144171816/b928e3cb-6ad2-4d58-9e10-b2b805280048)

SOURCE FOR SELECT MENU IMPLEMENTATION:  https://gist.github.com/lykn/a2b68cb790d6dad8ecff75b2aa450f23

When I tried using their original options exactly -

```
import discord 
from discord.ext import commands 

client=commands.Bot(command_prefix=commands.when_mentioned_or("."))

class Select(discord.ui.Select):
    def __init__(self):
        options=[
            discord.SelectOption(label="Option 1",emoji="👌",description="This is option 1!"),
            discord.SelectOption(label="Option 2",emoji="✨",description="This is option 2!"),
            discord.SelectOption(label="Option 3",emoji="🎭",description="This is option 3!")
            ]
        super().__init__(placeholder="Select an option",max_values=1,min_values=1,options=options)
    async def callback(self, interaction: discord.Interaction):
        await interaction.response.send_message(content=f"Your choice is {self.values[0]}!",ephemeral=True)

class SelectView(discord.ui.View):
    def __init__(self, *, timeout = 180):
        super().__init__(timeout=timeout)
        self.add_item(Select())

@client.command()
async def menu(ctx):
    await ctx.send("Menus!",view=SelectView())

token=""
client.run(token) 
```

still facing the same error -

```
PS C:\Users\panat\SE\Finbot\src> python .\discordBottest.py
2023-10-04 01:38:49 INFO     discord.client logging in using static token
2023-10-04 01:38:50 INFO     discord.gateway Shard ID None has connected to Gateway (Session ID: 95d00119d1605234e31b1a3b19b5b195).
2023-10-04 01:39:20 ERROR    discord.ui.view Ignoring exception in view <SelectView timeout=180 children=1> for item <Select placeholder='Select an option' min_values=1 max_values=1 disabled=False options=[<SelectOption label='Option 1' value='Option 1' description='This is option 1!' emoji=<PartialEmoji animated=False name='👌' id=None> default=False>, <SelectOption label='Option 2' value='Option 2' description='This is option 2!' emoji=<PartialEmoji animated=False name='✨' id=None> default=False>, <SelectOption label='Option 3' value='Option 3' description='This is option 3!' emoji=<PartialEmoji animated=False name='🎭' id=None> default=False>]>
Traceback (most recent call last):
  File "C:\Users\panat\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\ui\view.py", line 427, in _scheduled_task
    await item.callback(interaction)
  File "C:\Users\panat\SE\Finbot\src\discordBottest.py", line 74, in callback
    await interaction.response.send_message(content=f"Your choice is {self.values[0]}!",ephemeral=True)
  File "C:\Users\panat\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\interactions.py", line 801, in send_message
    await adapter.create_interaction_response(
  File "C:\Users\panat\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\webhook\async_.py", line 221, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In name: Username cannot contain "discord"
```

From my understanding, I think there is something wrong with the syntax in which the callback function is defined but was unable to find details or debug. Tried quite a few alternatives (https://guide.pycord.dev/interactions/ui-components/dropdowns) but no luck!

**Measures taken:**

1) posted the problem in https://gist.github.com/lykn/a2b68cb790d6dad8ecff75b2aa450f23 for any comments

2) Referring other sources to check for alternatives

**Comment by tpanati** [comment]
PR:

https://github.com/vyshnavi-adusumelli/FinBot/pull/33

Notes:

The application name in the developer portal was assigned as "Discord-Fin-Bot" so the username has Discord present in it which led to interaction failures and exceptions. The application name was fixed and the corresponding changes were tested using the discord.ui library and it worked as expected. The test results are attached in the PR above
